testing: allow kazoo to properly start zookeeper on Debian/Ubuntu
On Debian/Ubuntu, recent versions of zookeeper need to load slf4j to
work as expected. Otherwise, we get this error message on start:

```
Exception Exception in thread "main" in thread "main" Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactoryjava.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

        at org.apache.zookeeper.server.quorum.QuorumPeerMain.<clinit>(QuorumPeerMain.java:64)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.<clinit>(QuorumPeerMain.java:64)
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.<clinit>(QuorumPeerMain.java:64)Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
```